In [1]:
import pandas as pd
import json

In [2]:
data = pd.read_json("dati/prizes.json")

In [3]:
data

,year,category,overallMotivation,laureates
0,2018,physics,“for groundbreaking inventions in the field of...,"[{'id': '960', 'firstname': 'Arthur', 'surname..."
1,2018,medicine,NaN,"[{'id': '958', 'firstname': 'James P.', 'surna..."
2,2018,economics,NaN,"[{'id': '968', 'firstname': 'William D.', 'sur..."
3,2017,peace,NaN,"[{'id': '948', 'firstname': 'International Cam..."
4,2017,economics,NaN,"[{'id': '949', 'firstname': 'Richard H.', 'sur..."
...,...,...,...,...
585,1905,chemistry,NaN,"[{'id': '164', 'firstname': 'Johann Friedrich ..."
586,1904,peace,NaN,"[{'id': '467', 'firstname': 'Institut de droit..."
587,1901,physics,NaN,"[{'id': '1', 'firstname': 'Wilhelm Conrad', 's..."
588,1901,literature,NaN,"[{'id': '569', 'firstname': 'Sully', 'surname'..."
589,1901,peace,NaN,"[{'id': '462', 'firstname': 'Jean Henry', 'sur..."

In [4]:
with open('dati/prizes.json','r') as f:
    data = json.loads(f.read())
        
# Flatten data
df_nested_list = pd.json_normalize(data, record_path =['laureates'])

In [23]:
df_nested_list

,id,firstname,surname,motivation,share
0,960,Arthur,Ashkin,"""for the optical tweezers and their applicatio...",2
1,961,Gérard,Mourou,"""for their method of generating high-intensity...",4
2,962,Donna,Strickland,"""for their method of generating high-intensity...",4
3,958,James P.,Allison,"""for their discovery of cancer therapy by inhi...",2
4,959,Tasuku,Honjo,"""for their discovery of cancer therapy by inhi...",2
...,...,...,...,...,...
930,467,Institut de droit international (Institute of ...,,NaN,1
931,1,Wilhelm Conrad,Röntgen,"""in recognition of the extraordinary services ...",1
932,569,Sully,Prudhomme,"""in special recognition of his poetic composit...",1
933,462,Jean Henry,Dunant,NaN,2
934,463,Frédéric,Passy,NaN,2