In [1]:
import pandas as pd

In [2]:
dati = pd.read_csv("dati/sales.csv")

In [3]:
dati = dati.drop(['Unnamed: 0'], axis = 1)

In [4]:
dati.head(50)

   NomeAgente  Vendite  Quarto   Paese
0      Jacopo     1500       1      US
1       Marco      300       1   Japan
2        Tina      400       1  Brazil
3       Maria      500       1      UK
4         Mia      800       1     UAE
5       Tania      900       1     CAN
6        Mike     1000       1      US
7         Dan      900       1  Brazil
8      Jacopo     1000       2      US
9       Marco      500       2  Brazil
10       Tina      700       2   Japan
11      Maria       50       2  Brazil
12        Mia       60       2      UK
13      Tania      900       2     UAE
14       Mike      400       2      UK
15        Dan      500       2      UK
16     Jacopo     1000       3      US
17      Marco      900       3      US
18       Tina      750       3      US
19      Maria     2500       3   Japan
20        Mia      300       3  Brazil
21      Tania      800       3      UK
22       Mike      200       3     UAE
23        Dan      900       3     CAN
24     Jacopo     2000       4  Brazil
25      Marco      900       4      UK
26       Tina      250       4  Brazil
27      Maria      750       4   Japan
28        Mia       50       4      US
29      Tania      800       4   Japan
30       Mike     1000       4     CAN
31        Dan      400       4     UAE

##### Quanto ha venduto ogni agente ?

In [14]:
vendite_agente = dati.pivot_table(index= ["NomeAgente"], values = ["Vendite"], aggfunc = "sum")

In [15]:
vendite_agente

            Vendite
NomeAgente
Dan            2700
Jacopo         5500
Marco          2600
Maria          3800
Mia            1210
Mike           2600
Tania          3400
Tina           2100

#### Quanto sono le vendite totali per ogni mercato/paese?

In [16]:
vendite_paese = dati.pivot_table(index = "Paese", values = "Vendite", aggfunc = "sum")

In [17]:
vendite_paese

        Vendite
Paese
Brazil     4400
CAN        2800
Japan      5050
UAE        2300
UK         3160
US         6200

#### Massima vendita (valore) realizata da un agente/paese?

In [20]:
max_vendita_agente = dati.pivot_table(index = ["NomeAgente"], values = ["Vendite"], aggfunc="max")

In [21]:
max_vendita_agente

            Vendite
NomeAgente
Dan             900
Jacopo         2000
Marco           900
Maria          2500
Mia             800
Mike           1000
Tania           900
Tina            750

In [22]:
max_vendita_paese = dati.pivot_table(index = ["Paese"], values = ["Vendite"], aggfunc="max")

In [23]:
max_vendita_paese

        Vendite
Paese
Brazil     2000
CAN        1000
Japan      2500
UAE         900
UK          900
US         1500

In [24]:
vendite_ag_p = dati.pivot_table(index = ["NomeAgente", "Paese"], values = "Vendite")

In [25]:
vendite_ag_p

                       Vendite
NomeAgente Paese
Dan        Brazil   900.000000
           CAN      900.000000
           UAE      400.000000
           UK       500.000000
Jacopo     Brazil  2000.000000
           US      1166.666667
Marco      Brazil   500.000000
           Japan    300.000000
           UK       900.000000
           US       900.000000
Maria      Brazil    50.000000
           Japan   1625.000000
           UK       500.000000
Mia        Brazil   300.000000
           UAE      800.000000
           UK        60.000000
           US        50.000000
Mike       CAN     1000.000000
           UAE      200.000000
           UK       400.000000
           US      1000.000000
Tania      CAN      900.000000
           Japan    800.000000
           UAE      900.000000
           UK       800.000000
Tina       Brazil   325.000000
           Japan    700.000000
           US       750.000000

#### Qual è la media, mediana e il min vendite per paese ?

In [26]:
dati_agg_stats = dati.pivot_table(index = ["Paese"], values = ["Vendite"], aggfunc={"mean", "median", "min"})

In [27]:
dati_agg_stats

            Vendite
               mean  median    min
Paese
Brazil   628.571429   400.0   50.0
CAN      933.333333   900.0  900.0
Japan   1010.000000   750.0  300.0
UAE      575.000000   600.0  200.0
UK       526.666667   500.0   60.0
US       885.714286  1000.0   50.0

In [28]:
dati_agg_stats_ag = dati.pivot_table(index = ["NomeAgente"], values = ["Vendite"], aggfunc={"mean", "median", "min"})

In [29]:

dati_agg_stats_ag

           Vendite
              mean  median     min
NomeAgente
Dan          675.0   700.0   400.0
Jacopo      1375.0  1250.0  1000.0
Marco        650.0   700.0   300.0
Maria        950.0   625.0    50.0
Mia          302.5   180.0    50.0
Mike         650.0   700.0   200.0
Tania        850.0   850.0   800.0
Tina         525.0   550.0   250.0